CREATE TABLE training_applicants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    training_type VARCHAR(255),
    candidate_type VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    prefix VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    care_of VARCHAR(255),
    father_mother_husband_name VARCHAR(255),
    gender VARCHAR(255),
    date_of_birth DATE,
    aadhaar_no VARCHAR(20),
    physically_challenged ENUM('Yes', 'No'),
    community VARCHAR(255),
    qualification VARCHAR(255),
    photo VARCHAR(255),
    address TEXT,
    district VARCHAR(255),
    pincode VARCHAR(10),
    contact_no VARCHAR(15),
    agree_to_privacy_notice BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
