<?php

return [

     'notes' => [
          'default' => [
               'Download the template and fill the data and upload it.',
               'All mandatory fields should be given.',
               'Email should be given in correct format.',                        
          ],
          'entrepreneur' => [
               'Candidate field should have one of the values (Student, SpokeStudent, Entrepreneur, Startup, Employed, Unemployed)',
               'If Candidate type field is student then, student type field  must be college or school.',
               'If Student type field is college then, you must provide hub institution, course name and year',
               'If Student type field is school then, you must provide school name and standard.',
               'If Candidate type field is SpokeStudent then, you must provide hub institution and spoke college name.',
               'If Candidate type field is other than Student and SpokeStudent then, you must provide qualification.',
               'Prefix field should have one of the following values (Mr./ Mrs./ Miss./ Thiru./ Tmt./ Selvi./ Dr./ Prof.)',
               'Care of field should have one of the values (S/o, D/o, W/o)',
               'Gender field should have one of the values (Male, Female, Transgender)',
               'DOB should be in specified format(dd-mm-yyyy).',
               "The Mobile Number field should contain 10 digits.", 
               "Pysically challenged field should have one of the following values (Yes, No)",
               'Religion field should have one of the values (Hindu, Muslim, Christian, Buddhist, Jain, Other Religion)',
               'Community field should have one of the values (BC, MBC, FC, SC, ST)',
          ],
          'trainee' => [
               'Candidate field should have one of the values (Student, SpokeStudent, Entrepreneur, Startup, Employed, Unemployed)',
               'If Candidate type field is student then, student type field  must be college or school.',
               'If Student type field is college then, you must provide hub institution, course name and year',
               'If Student type field is school then, you must provide school name and standard.',
               'If Candidate type field is SpokeStudent then, you must provide hub institution and spoke college name.',
               'If Candidate type field is other than Student and SpokeStudent then, you must provide qualification.',
               'Email field should be unique and same Email should be given in "basic sheet" and "program sheet".',
               'Prefix field should have one of the following values (Mr./ Mrs./ Miss./ Thiru./ Tmt./ Selvi./ Dr./ Prof.)',
               'Care of field should have one of the values (S/o, D/o, W/o)',
               'Gender field should have one of the values (Male, Female, Transgender)',
               'DOB should be in specified format(dd-mm-yyyy).',
               "The Mobile Number field should contain 10 digits.", 
               "Pysically challenged field should have one of the following values (Yes, No)",
               'Religion field should have one of the values (Hindu, Muslim, Christian, Buddhist, Jain, Other Religion)',
               'Community field should have one of the values (BC, MBC, FC, SC, ST)',
          ],     
     ], 

     'Impiger\Entrepreneur\Models\Entrepreneur' => [
          'fields' =>[
               'email' => ['field' => 'email_id','type'=>'text'],
               //'email' => ['field' => 'email','type'=>'text'],
			'password' => ['field' => 'password','type'=>'text'],
			'prefix_id' => ['field' => 'prefix','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'prefixes']],
			'name' => ['field' => 'name','type'=>'text'],
			'gender_id' => ['field' => 'gender','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'gender']],
			'dob' => ['field' => 'dob', 'type'=>'date'],
               'mobile' => ['field' => 'contact','type'=>'text'],
               //'mobile' => ['field' => 'mobile','type'=>'text'],
               'community' => ['field' => 'community','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'community']],
               'religion_id' => ['field' => 'religion','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'religion']],
               'care_of' => ['field' => 'care_of','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'care_of']],
			'father_name' => ['field' => 'father_name','type'=>'text'],
			'district_id' => ['field' => 'district','type'=>'select','dependant'=>['district','name'],'whrcond' => []],
               'pincode' => ['field' => 'pincode','type'=>'text'],
			// 'physically_challenged' => ['field' => 'physically_challenged','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'gender']],
			'physically_challenged' => ['field' => 'physically_challenged','type'=>'text'],
			'candidate_type_id' => ['field' => 'candidate_type','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'candidate_type']],
			'student_type_id' => ['field' => 'student_type','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'student_type']],
			'student_school_name' => ['field' => 'student_school_name','type'=>'text'],
			'student_standard_name' => ['field' => 'student_standard_name','type'=>'text'],
			'student_college_name' => ['field' => 'student_college_name','type'=>'text'],
			'student_course_name' => ['field' => 'student_course_name','type'=>'text'],
			'hub_institution_id' => ['field' => 'hub_institution','type'=>'select','dependant'=>['hub_institutions','name'],'whrcond' => []],
			'student_year' => ['field' => 'student_year','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'course_year']],
			'spoke_registration_id' => ['field' => 'spoke_college_name','type'=>'select','dependant'=>['spoke_registration','name'],'whrcond' => []],
			'qualification_id' => ['field' => 'student_type','type'=>'select','dependant'=>['qualifications','name'],'whrcond' => []],
			//'qualification_id' => ['field' => 'qualification','type'=>'select','dependant'=>['qualifications','name'],'whrcond' => []],
			'photo_path' => ['field' => 'photo_path','type'=>'text'],
			'aadhaar_no' => ['field' => 'aadhaar_no','type'=>'text'],
			'address' => ['field' => 'address','type'=>'text'],
			'activity_name' => ['field' => 'activity_name','type'=>'text'],
          ],
          'action'=>'coreUser',
          'role_slug'=> 'candidate'
          // 'role_slug'=> CANDIDATE_ROLE_SLUG
     ],

     // 'Impiger\Entrepreneur\Models\Trainee' => [
     //      'fields' =>[
     //           'user_id' => ['field' => 'entrepreneur','type'=>'select','dependant'=>['users','email'],'whrcond' => []],
     //           'entrepreneur_id' => ['field' => 'entrepreneur','type'=>'select','dependant'=>['entrepreneurs','email'],'whrcond' => []],
     //           'division_id' => ['field' => 'division','type'=>'select','dependant'=>['divisions','name'],'whrcond' => []],
     //           'financial_year_id' => ['field' => 'financial_year','type'=>'select','dependant'=>['financial_year','session_year'],'whrcond' => []],
     //           'annual_action_plan_id' => ['field' => 'annual_action_plan','type'=>'select','dependant'=>['annual_action_plan','name'],'whrcond' => []],
     //           'training_title_id' => ['field' => 'training_title','type'=>'select','dependant'=>['training_title','name'],'whrcond' => []],
     //      ]
     // ],   
     
     'Impiger\Entrepreneur\Models\Trainee' => [
          'Impiger\Entrepreneur\Models\Entrepreneur' => [
               'fields' =>[
                    'email' => ['field' => 'email','type'=>'text','filter'=>1],
                    //'email' => ['field' => 'email_id','type'=>'text','filter'=>1],
                    'password' => ['field' => 'password','type'=>'text'],
                    'prefix_id' => ['field' => 'prefix','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'prefixes']],
                    'name' => ['field' => 'name','type'=>'text'],
                    'gender_id' => ['field' => 'gender','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'gender']],
                    'dob' => ['field' => 'dob', 'type'=>'date'],
                    'mobile' => ['field' => 'mobile','type'=>'text'],
                    //'mobile' => ['field' => 'contact','type'=>'text'],
                    'community' => ['field' => 'community','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'community']],
                    'religion_id' => ['field' => 'religion','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'religion']],
                    'care_of' => ['field' => 'care_of','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'care_of']],
                    'father_name' => ['field' => 'father_name','type'=>'text'],
                    'district_id' => ['field' => 'district','type'=>'select','dependant'=>['district','name'],'whrcond' => []],
                    'pincode' => ['field' => 'pincode','type'=>'text'],
                    // 'physically_challenged' => ['field' => 'physically_challenged','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'gender']],
                    'physically_challenged' => ['field' => 'physically_challenged','type'=>'text'],
                    'candidate_type_id' => ['field' => 'candidate_type','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'candidate_type']],
                    'student_type_id' => ['field' => 'student_type','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'student_type']],
                    'student_school_name' => ['field' => 'student_school_name','type'=>'text'],
                    'student_standard_name' => ['field' => 'student_standard_name','type'=>'text'],
                    'student_college_name' => ['field' => 'student_college_name','type'=>'text'],
                    'student_course_name' => ['field' => 'student_course_name','type'=>'text'],
                    'hub_institution_id' => ['field' => 'hub_institution','type'=>'select','dependant'=>['hub_institutions','name'],'whrcond' => []],
                    'student_year' => ['field' => 'student_year','type'=>'select','dependant'=>['attribute_options','name'],'whrcond' => ['attribute'=>'course_year']],
                    'spoke_registration_id' => ['field' => 'spoke_college_name','type'=>'select','dependant'=>['spoke_registration','name'],'whrcond' => []],
                    'qualification_id' => ['field' => 'qualification','type'=>'select','dependant'=>['qualifications','name'],'whrcond' => []],
			        //'qualification_id' => ['field' => 'student_type','type'=>'select','dependant'=>['qualifications','name'],'whrcond' => []],
                    'photo_path' => ['field' => 'photo_path','type'=>'text'],
                    'aadhaar_no' => ['field' => 'aadhaar_no','type'=>'text'],
                    'address' => ['field' => 'address','type'=>'text'],
                    'activity_name' => ['field' => 'activity_name','type'=>'text'],
               ],
               'action'=>'coreUser',
               'role_slug'=> 'candidate'
               // 'role_slug'=> CANDIDATE_ROLE_SLUG
          ],
          'Impiger\Entrepreneur\Models\Trainee' => [
               'reference_keys' => ['email','trainee_email'],
               'parent_module' => 'Impiger\Entrepreneur\Models\Entrepreneur',
               'reference_field' => 'entrepreneur_id',
               'fields' =>[
                    'user_id' => ['field' => 'trainee_email','type'=>'select','dependant'=>['users','email'],'whrcond' => []],
                    'entrepreneur_id' => ['field' => 'trainee_email','type'=>'select','dependant'=>['entrepreneurs','email'],'whrcond' => []],
                    'division_id' => ['field' => 'division','type'=>'select','dependant'=>['divisions','name'],'whrcond' => []],
                    'financial_year_id' => ['field' => 'financial_year','type'=>'select','dependant'=>['financial_year','session_year'],'whrcond' => []],
                    'annual_action_plan_id' => ['field' => 'annual_action_plan','type'=>'select','dependant'=>['annual_action_plan','name'],'whrcond' => []],
                    // 'training_title_id' => ['field' => 'training_title','type'=>'select','dependant'=>['training_title','name'],'whrcond' => []],
                    'training_title_id' => ['field' => 'training_title_code','type'=>'select','dependant'=>['training_title','code'],'whrcond' => []],
               ]
          ], 
     ],
];

