<?php

namespace Impiger\TrainingTitleFinancialDetail\Repositories\Caches;

use Impiger\Support\Repositories\Caches\CacheAbstractDecorator;
use Impiger\TrainingTitleFinancialDetail\Repositories\Interfaces\TrainingTitleFinancialDetailInterface;

class TrainingTitleFinancialDetailCacheDecorator extends CacheAbstractDecorator implements TrainingTitleFinancialDetailInterface
{

}
